/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
export function MainModel(props) {
   const { nodes, materials } = useGLTF("models/SCENELOGO.glb");

   const v = useMemo(() => {
      return new THREE.MeshStandardMaterial({
         color: "blue",
         //  emissive: "blue",
         emissiveIntensity: 13,
         roughness: 0,
         metalness: 0,
         side: THREE.DoubleSide,
      });
   }, []);
   return (
      <group {...props} dispose={null}>
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group37982561.geometry}
            material={materials["mat16.002"]}
            position={[0.412, 0.041, 0.119]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.2}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group810781124.geometry}
            material={materials["mat16.002"]}
            position={[0.411, 0.041, -0.121]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.2}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group2015598450.geometry}
            material={materials["mat22.001"]}
            position={[-0.746, 0.079, -0.004]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.552}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group1841975321.geometry}
            material={materials["mat22.001"]}
            position={[-0.683, 0.079, -0.004]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.552}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group494692606.geometry}
            material={materials["mat22.001"]}
            position={[-0.619, 0.079, -0.004]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.552}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group1280261175.geometry}
            material={materials["mat23.001"]}
            position={[-0.83, 0.009, 0.151]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.552}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group949196155.geometry}
            material={materials["mat23.001"]}
            position={[-0.535, 0.009, 0.151]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.552}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group815604096.geometry}
            material={materials["mat23.001"]}
            position={[-0.535, 0.009, -0.159]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.552}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group1740984658.geometry}
            material={materials["mat23.001"]}
            position={[-0.535, 0.009, -0.16]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.552}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group417174269.geometry}
            material={materials["mat23.001"]}
            position={[-0.83, 0.009, -0.159]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.552}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group1145278412.geometry}
            material={materials["mat16.002"]}
            position={[-0.535, 0.024, -0.004]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.552}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group518932168.geometry}
            material={materials["mat16.002"]}
            position={[-0.829, 0.024, -0.005]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.552}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group1496666282.geometry}
            material={materials["mat23.001"]}
            position={[-0.83, 0.009, -0.159]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.552}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group161396369.geometry}
            material={materials["mat15.003"]}
            position={[0.412, 0.071, -0.004]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.2}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group413408637.geometry}
            material={materials["mat16.002"]}
            position={[1.318, 0.041, -0.004]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.2}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group323396810.geometry}
            material={materials["mat16.002"]}
            position={[-0.494, 0.041, -0.004]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.2}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group512570650.geometry}
            material={materials["mat23.001"]}
            position={[0.412, 0.089, -0.004]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.2}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group884165777.geometry}
            material={materials["mat23.001"]}
            position={[-0.5, 0.071, -0.004]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.2}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group160355870.geometry}
            material={materials["mat23.001"]}
            position={[0.412, 0.053, -0.004]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.2}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group1508755916.geometry}
            material={materials["mat23.001"]}
            position={[1.324, 0.071, -0.004]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.2}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group1807440170.geometry}
            material={materials["mat22.001"]}
            position={[-0.812, 0.079, -0.004]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.552}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group271065018.geometry}
            material={materials["mat22.001"]}
            position={[-0.563, 0.079, -0.004]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.552}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group848837919.geometry}
            material={materials["mat15.003"]}
            position={[-0.683, 0.056, -0.004]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.552}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group653319785.geometry}
            material={materials["mat23.001"]}
            position={[-0.83, 0.009, 0.151]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.552}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group1005767962.geometry}
            material={materials["mat23.001"]}
            position={[-0.535, 0.009, 0.151]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.552}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes["3DGeom-2"].geometry}
            material={v}
            position={[-0.928, 0.836, 0]}
            scale={0.032}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes["3DGeom-3"].geometry}
            material={v}
            position={[-0.753, 0.261, 0]}
            scale={0.032}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group1280261175002.geometry}
            material={materials["mat23.005"]}
            position={[-0.465, 0.01, 0.151]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.552}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group1496666282002.geometry}
            material={materials["mat23.005"]}
            position={[-0.465, 0.01, -0.159]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.552}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group417174269002.geometry}
            material={materials["mat23.005"]}
            position={[-0.465, 0.01, -0.159]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.552}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group518932168002.geometry}
            material={materials["mat16.006"]}
            position={[-0.465, 0.025, -0.005]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.552}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group653319785002.geometry}
            material={materials["mat23.005"]}
            position={[-0.465, 0.01, 0.151]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.552}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group1280261175004.geometry}
            material={materials["mat23.007"]}
            position={[0.67, 0.008, 0.117]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.387}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group1496666282004.geometry}
            material={materials["mat23.007"]}
            position={[0.67, 0.007, -0.13]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.387}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group417174269004.geometry}
            material={materials["mat23.007"]}
            position={[0.67, 0.007, -0.131]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.387}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group518932168004.geometry}
            material={materials["mat16.008"]}
            position={[0.671, 0.021, -0.005]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.185}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group653319785004.geometry}
            material={materials["mat23.007"]}
            position={[0.67, 0.008, 0.118]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.387}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group1280261175006.geometry}
            material={materials["mat23.009"]}
            position={[2.108, 0.008, 0.117]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.387}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group1496666282006.geometry}
            material={materials["mat23.009"]}
            position={[2.108, 0.007, -0.13]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.387}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group417174269006.geometry}
            material={materials["mat23.009"]}
            position={[2.108, 0.007, -0.131]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.387}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group518932168006.geometry}
            material={materials["mat16.010"]}
            position={[2.108, 0.021, -0.005]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.185}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group653319785006.geometry}
            material={materials["mat23.009"]}
            position={[2.108, 0.008, 0.118]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.387}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group1280261175008.geometry}
            material={materials["mat23.011"]}
            position={[3.801, 0.008, 0.117]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.387}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group1496666282008.geometry}
            material={materials["mat23.011"]}
            position={[3.801, 0.007, -0.13]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.387}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group417174269008.geometry}
            material={materials["mat23.011"]}
            position={[3.801, 0.007, -0.131]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.387}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group518932168008.geometry}
            material={materials["mat16.012"]}
            position={[3.801, 0.021, -0.005]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.185}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.group653319785008.geometry}
            material={materials["mat23.011"]}
            position={[3.801, 0.008, 0.118]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.387}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.LHS.geometry}
            material={materials["Material.002"]}
            position={[-0.475, 1.032, 0]}
            scale={0.344}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.LHS001.geometry}
            material={materials["Material.001"]}
            position={[-0.552, 1.026, 0]}
            scale={0.344}
         />
      </group>
   );
}

useGLTF.preload("models/SCENELOGO.glb");
